// @ts-nocheck
import * as __fd_glob_51 from "../docs/technical/waitlist.md?collection=docs"
import * as __fd_glob_50 from "../docs/technical/notifications.md?collection=docs"
import * as __fd_glob_49 from "../docs/technical/navi-ops-cli.md?collection=docs"
import * as __fd_glob_48 from "../docs/technical/mc-telegram-mcchat-integration.md?collection=docs"
import * as __fd_glob_47 from "../docs/technical/kanban-board.md?collection=docs"
import * as __fd_glob_46 from "../docs/technical/connection-wizard.md?collection=docs"
import * as __fd_glob_45 from "../docs/technical/chat-threads.md?collection=docs"
import * as __fd_glob_44 from "../docs/technical/billing.md?collection=docs"
import * as __fd_glob_43 from "../docs/technical/billing-stripe.md?collection=docs"
import * as __fd_glob_42 from "../docs/technical/auth-provider.md?collection=docs"
import * as __fd_glob_41 from "../docs/technical/aipipe-integration.md?collection=docs"
import * as __fd_glob_40 from "../docs/technical/ai-routing.md?collection=docs"
import * as __fd_glob_39 from "../docs/technical/agent-stats.md?collection=docs"
import * as __fd_glob_38 from "../docs/technical/activity-feed.md?collection=docs"
import * as __fd_glob_37 from "../docs/insights/2026-02-21-stripe-coding-agents-thousand-prs.md?collection=docs"
import * as __fd_glob_36 from "../docs/guides/self-hosting.md?collection=docs"
import * as __fd_glob_35 from "../docs/guides/introduction.md?collection=docs"
import * as __fd_glob_34 from "../docs/guides/how-to-use.md?collection=docs"
import * as __fd_glob_33 from "../docs/guides/getting-started.md?collection=docs"
import * as __fd_glob_32 from "../docs/guides/developer-onboarding.md?collection=docs"
import * as __fd_glob_31 from "../docs/guides/dashboard-guide.md?collection=docs"
import * as __fd_glob_30 from "../docs/features/waitlist.md?collection=docs"
import * as __fd_glob_29 from "../docs/features/notifications.md?collection=docs"
import * as __fd_glob_28 from "../docs/features/navi-ops-cli.md?collection=docs"
import * as __fd_glob_27 from "../docs/features/mission-control-layout.md?collection=docs"
import * as __fd_glob_26 from "../docs/features/memory-tab.md?collection=docs"
import * as __fd_glob_25 from "../docs/features/kanban-board.md?collection=docs"
import * as __fd_glob_24 from "../docs/features/connection-wizard.md?collection=docs"
import * as __fd_glob_23 from "../docs/features/chat-threads.md?collection=docs"
import * as __fd_glob_22 from "../docs/features/billing.md?collection=docs"
import * as __fd_glob_21 from "../docs/features/billing-stripe.md?collection=docs"
import * as __fd_glob_20 from "../docs/features/auth-provider.md?collection=docs"
import * as __fd_glob_19 from "../docs/features/aipipe-routing-benchmark.md?collection=docs"
import * as __fd_glob_18 from "../docs/features/aipipe-integration.md?collection=docs"
import * as __fd_glob_17 from "../docs/features/ai-routing.md?collection=docs"
import * as __fd_glob_16 from "../docs/features/agent-stats.md?collection=docs"
import * as __fd_glob_15 from "../docs/features/activity-feed.md?collection=docs"
import * as __fd_glob_14 from "../docs/api-reference/tasks.md?collection=docs"
import * as __fd_glob_13 from "../docs/api-reference/overview.md?collection=docs"
import * as __fd_glob_12 from "../docs/index.mdx?collection=docs"
import * as __fd_glob_11 from "../docs/dashboard-guide.md?collection=docs"
import * as __fd_glob_10 from "../docs/SETUP.md?collection=docs"
import * as __fd_glob_9 from "../docs/SECURITY.md?collection=docs"
import * as __fd_glob_8 from "../docs/OPERATIONS.md?collection=docs"
import * as __fd_glob_7 from "../docs/DOCS-SYSTEM-PROPOSAL.md?collection=docs"
import * as __fd_glob_6 from "../docs/ARCHITECTURE.md?collection=docs"
import * as __fd_glob_5 from "../docs/API.md?collection=docs"
import { default as __fd_glob_4 } from "../docs/technical/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../docs/guides/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../docs/features/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../docs/api-reference/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "docs", {"meta.json": __fd_glob_0, "api-reference/meta.json": __fd_glob_1, "features/meta.json": __fd_glob_2, "guides/meta.json": __fd_glob_3, "technical/meta.json": __fd_glob_4, }, {"API.md": __fd_glob_5, "ARCHITECTURE.md": __fd_glob_6, "DOCS-SYSTEM-PROPOSAL.md": __fd_glob_7, "OPERATIONS.md": __fd_glob_8, "SECURITY.md": __fd_glob_9, "SETUP.md": __fd_glob_10, "dashboard-guide.md": __fd_glob_11, "index.mdx": __fd_glob_12, "api-reference/overview.md": __fd_glob_13, "api-reference/tasks.md": __fd_glob_14, "features/activity-feed.md": __fd_glob_15, "features/agent-stats.md": __fd_glob_16, "features/ai-routing.md": __fd_glob_17, "features/aipipe-integration.md": __fd_glob_18, "features/aipipe-routing-benchmark.md": __fd_glob_19, "features/auth-provider.md": __fd_glob_20, "features/billing-stripe.md": __fd_glob_21, "features/billing.md": __fd_glob_22, "features/chat-threads.md": __fd_glob_23, "features/connection-wizard.md": __fd_glob_24, "features/kanban-board.md": __fd_glob_25, "features/memory-tab.md": __fd_glob_26, "features/mission-control-layout.md": __fd_glob_27, "features/navi-ops-cli.md": __fd_glob_28, "features/notifications.md": __fd_glob_29, "features/waitlist.md": __fd_glob_30, "guides/dashboard-guide.md": __fd_glob_31, "guides/developer-onboarding.md": __fd_glob_32, "guides/getting-started.md": __fd_glob_33, "guides/how-to-use.md": __fd_glob_34, "guides/introduction.md": __fd_glob_35, "guides/self-hosting.md": __fd_glob_36, "insights/2026-02-21-stripe-coding-agents-thousand-prs.md": __fd_glob_37, "technical/activity-feed.md": __fd_glob_38, "technical/agent-stats.md": __fd_glob_39, "technical/ai-routing.md": __fd_glob_40, "technical/aipipe-integration.md": __fd_glob_41, "technical/auth-provider.md": __fd_glob_42, "technical/billing-stripe.md": __fd_glob_43, "technical/billing.md": __fd_glob_44, "technical/chat-threads.md": __fd_glob_45, "technical/connection-wizard.md": __fd_glob_46, "technical/kanban-board.md": __fd_glob_47, "technical/mc-telegram-mcchat-integration.md": __fd_glob_48, "technical/navi-ops-cli.md": __fd_glob_49, "technical/notifications.md": __fd_glob_50, "technical/waitlist.md": __fd_glob_51, });